// TODO: test v1::documents::alignment
// TODO: test v1::documents::auto_text
// TODO: test v1::documents::background
// TODO: test v1::documents::background_suggestion_state
// TODO: test v1::documents::baseline_offset
// TODO: test v1::documents::body
// TODO: test v1::documents::bullet
// TODO: test v1::documents::bullet_alignment
// TODO: test v1::documents::bullet_suggestion_state
// TODO: test v1::documents::color
// TODO: test v1::documents::column_break
// TODO: test v1::documents::column_separator_style
// TODO: test v1::documents::content_alignment
// TODO: test v1::documents::content_direction
// TODO: test v1::documents::crop_properties
// TODO: test v1::documents::crop_properties_suggestion_state
// TODO: test v1::documents::dash_style
// TODO: test v1::documents::dimension
// TODO: test v1::documents::document
// TODO: test v1::documents::document_style
// TODO: test v1::documents::document_style_suggestion_state
// TODO: test v1::documents::embedded_drawing_properties
// TODO: test v1::documents::embedded_drawing_properties_suggestion_state
// TODO: test v1::documents::embedded_object
// TODO: test v1::documents::embedded_object_border
// TODO: test v1::documents::embedded_object_border_suggestion_state
// TODO: test v1::documents::embedded_object_properties
// TODO: test v1::documents::embedded_object_suggestion_state
// TODO: test v1::documents::equation
// TODO: test v1::documents::footer
// TODO: test v1::documents::footnote
// TODO: test v1::documents::footnote_reference
// TODO: test v1::documents::glyph_type
// TODO: test v1::documents::header
// TODO: test v1::documents::horizontal_rule
// TODO: test v1::documents::image_properties
// TODO: test v1::documents::image_properties_suggestion_state
// TODO: test v1::documents::inline_object
// TODO: test v1::documents::inline_object_element
// TODO: test v1::documents::inline_object_properties
// TODO: test v1::documents::inline_object_properties_suggestion_state
// TODO: test v1::documents::link
// TODO: test v1::documents::link_destrination
// TODO: test v1::documents::linked_content_reference
// TODO: test v1::documents::linked_content_reference_reference
// TODO: test v1::documents::linked_content_reference_suggestion_state
// TODO: test v1::documents::list
// TODO: test v1::documents::list_properties
// TODO: test v1::documents::list_properties_suggestion_state
// TODO: test v1::documents::named_range
// TODO: test v1::documents::named_ranges
// TODO: test v1::documents::named_style
// TODO: test v1::documents::named_style_suggestion_state
// TODO: test v1::documents::named_style_type
// TODO: test v1::documents::named_styles
// TODO: test v1::documents::named_styles_suggestion_state
// TODO: test v1::documents::nesting_level
// TODO: test v1::documents::nesting_level_glyph_kind
// TODO: test v1::documents::nesting_level_suggestion_state
// TODO: test v1::documents::object_references
// TODO: test v1::documents::optional_color
// TODO: test v1::documents::page_break
// TODO: test v1::documents::paragraph
// TODO: test v1::documents::paragraph_border
// TODO: test v1::documents::paragraph_element
// TODO: test v1::documents::paragraph_element_content
// TODO: test v1::documents::paragraph_style
// TODO: test v1::documents::paragraph_style_suggestion_state
// TODO: test v1::documents::person
// TODO: test v1::documents::person_properties
// TODO: test v1::documents::positioned_object
// TODO: test v1::documents::positioned_object_layout
// TODO: test v1::documents::positioned_object_positioning
// TODO: test v1::documents::positioned_object_positioning_suggestion_state
// TODO: test v1::documents::positioned_object_properties
// TODO: test v1::documents::positioned_object_properties_suggestion_state
// TODO: test v1::documents::property_state
// TODO: test v1::documents::range
// TODO: test v1::documents::request::Request
// TODO: test v1::documents::request::bullet_glyph_preset;
// TODO: test v1::documents::request::delete_content_range_request;
// TODO: test v1::documents::request::end_of_segument_location;
// TODO: test v1::documents::request::insert_inline_image_request;
// TODO: test v1::documents::request::insert_inline_image_request_insertion_location;
// TODO: test v1::documents::request::insert_text_request;
// TODO: test v1::documents::request::insert_text_request_insertion_location;
// TODO: test v1::documents::request::location;
// TODO: test v1::documents::request::replace_all_text_request;
// TODO: test v1::documents::request::replace_all_text_request_criteria;
// TODO: test v1::documents::request::request_request;
// TODO: test v1::documents::request::substring_match_criteria;
// TODO: test v1::documents::rgb_color
// TODO: test v1::documents::rich_link
// TODO: test v1::documents::rich_link_properties
// TODO: test v1::documents::section_break
// TODO: test v1::documents::section_column_properties
// TODO: test v1::documents::section_style
// TODO: test v1::documents::section_type
// TODO: test v1::documents::shading
// TODO: test v1::documents::shading_suggestion_state
// TODO: test v1::documents::sheets_chart_reference
// TODO: test v1::documents::sheets_chart_reference_suggestion_state
// TODO: test v1::documents::size
// TODO: test v1::documents::size_suggestion_state
// TODO: test v1::documents::spacing_mode
// TODO: test v1::documents::structural_element
// TODO: test v1::documents::structural_element_content
// TODO: test v1::documents::suggested_bullet
// TODO: test v1::documents::suggested_document_style
// TODO: test v1::documents::suggested_inline_object_properties
// TODO: test v1::documents::suggested_list_properties
// TODO: test v1::documents::suggested_named_styles
// TODO: test v1::documents::suggested_paragraph_style
// TODO: test v1::documents::suggested_positioned_object_properties
// TODO: test v1::documents::suggested_table_cell_style
// TODO: test v1::documents::suggested_table_row_style
// TODO: test v1::documents::suggested_text_style
// TODO: test v1::documents::suggestions_view_mode
// TODO: test v1::documents::tab_stop
// TODO: test v1::documents::tab_stop_alignment
// TODO: test v1::documents::table
// TODO: test v1::documents::table_cell
// TODO: test v1::documents::table_cell_border
// TODO: test v1::documents::table_cell_style
// TODO: test v1::documents::table_cell_style_suggestion_state
// TODO: test v1::documents::table_column_properties
// TODO: test v1::documents::table_of_contents
// TODO: test v1::documents::table_row
// TODO: test v1::documents::table_row_style
// TODO: test v1::documents::table_row_style_suggestion_state
// TODO: test v1::documents::table_style
// TODO: test v1::documents::text_run
// TODO: test v1::documents::text_style
// TODO: test v1::documents::text_style_suggestion_state
// TODO: test v1::documents::r#type
// TODO: test v1::documents::unit
// TODO: test v1::documents::weighted_font_family
// TODO: test v1::documents::width_type
